apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../application

namespace: playmoney
commonLabels:
  environment: playmoney

configMapGenerator:
  - behavior: merge
    envs:
      - environment
    name: frontend-config

patches:
  - resourcesPatch.yaml
  - prodConfigPatch.yaml
